# interview imp questions 
* what is the diff between .fit transform and transform?

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [79]:
df = pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\Dataset\train_titanic_dataset.csv")
df.sample(5)

PassengerId  Survived  Pclass                            Name     Sex  \
217          218         0       2    Jacobsohn, Mr. Sidney Samuel    male   
502          503         0       3  O'Sullivan, Miss. Bridget Mary  female   
382          383         0       3              Tikkanen, Mr. Juho    male   
460          461         1       1             Anderson, Mr. Harry    male   
609          610         1       1       Shutes, Miss. Elizabeth W  female   

      Age  SibSp  Parch             Ticket      Fare Cabin Embarked  
217  42.0      1      0             243847   27.0000   NaN        S  
502   NaN      0      0             330909    7.6292   NaN        Q  
382  32.0      0      0  STON/O 2. 3101293    7.9250   NaN        S  
460  48.0      0      0              19952   26.5500   E12        S  
609  40.0      0      0           PC 17582  153.4625  C125        S

In [80]:
df.shape

(891, 12)

In [81]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace = True)

In [82]:
df.shape

(891, 8)

In [4]:
df.sample(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
857         1       1    male  51.0      0      0  26.5500        S
477         0       3    male  29.0      1      0   7.0458        S
113         0       3  female  20.0      1      0   9.8250        S
534         0       3  female  30.0      0      0   8.6625        S
818         0       3    male  43.0      0      0   6.4500        S

# train_test_split

In [87]:
x = df.iloc[:,1:8]
y = df.iloc[:,0]

In [88]:

x_train,x_test,y_train,y_test= train_test_split(x,y,random_state=42,test_size = 0.2)

In [89]:
x_train.shape

(712, 7)

In [90]:
x_test.shape

(179, 7)

In [91]:
y_train.shape

(712,)

In [92]:
y_test.shape

(179,)

# missing value checking

In [93]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

# lets fill the misiing values

In [94]:
# simple imputer creating object

si_imp_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')



In [95]:
# simple imputer in age will fill misiing values with mean

x_train_age = si_imp_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])


In [96]:
# simple imputer in Embarked will be fill with most frequent

x_test_age = si_imp_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])


In [97]:
# lest check out are the misiing values fill with null or not
x_train_embarked


array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [98]:
x_test_age

array([[29.49884615],
       [31.        ],
       [20.        ],
       [ 6.        ],
       [14.        ],
       [26.        ],
       [29.49884615],
       [16.        ],
       [16.        ],
       [19.        ],
       [37.        ],
       [44.        ],
       [29.49884615],
       [30.        ],
       [36.        ],
       [16.        ],
       [42.        ],
       [29.49884615],
       [27.        ],
       [47.        ],
       [24.        ],
       [34.        ],
       [19.        ],
       [20.        ],
       [29.49884615],
       [10.        ],
       [40.        ],
       [31.        ],
       [ 4.        ],
       [31.        ],
       [19.        ],
       [22.        ],
       [29.49884615],
       [29.49884615],
       [18.        ],
       [27.        ],
       [28.        ],
       [29.49884615],
       [30.        ],
       [29.49884615],
       [21.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [45.        ],
       [16

# One hot encoding


In [109]:
# tum alag object create krke embarked aur sex ke upar one hot encode q perform kr rhe ho?
# ans:- kyoki esme missing values hai embarked vale column me 
# but aab puchoge ki last avle esme hi toh embarked vale column me perform kiya hai na?
# ans:- original vale me koe changes nhi hai voh object crete kiya hai humne uska 
# sparse by default true rhta hai

# sparse by defalult true rhta hai and if true rha toh sparse metrics will be created 
# and handle_unknown = 'ignore' mean age future me values create hota hai toh use voh 0 creeate krega

ohe_sex = OneHotEncoder(sparse = False,handle_unknown = 'ignore')
ohe_embarked = OneHotEncoder(sparse = False,handle_unknown = 'ignore')

# x_train me hum fit transform krte hai
x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

# x_test me sirf transform krte hai
x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)







In [110]:
x_train_sex
# hum 'drop = first' q nhi liye kyoki hum d.t algorithm used krne wale hai so multicolinearity 
# koe problem nhi uspe effect nhi krta linear li solve nhi kr rhe hai hum.

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [111]:
x_train_embarked


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

# concatenate the all the array that you got 

In [112]:
x_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [113]:
# we dropping the column of sex,age,embarked why?
# ans:- because we alredy transform the columns into missing into the simple imputer and embarked converted 
#      into the one hot encode taht why

x_train_remain = x_train.drop(columns=['Sex','Age','Embarked'])
x_test_remain  = x_test.drop(columns=['Sex','Age','Embarked'])


In [114]:
x_test_remain.shape

(179, 4)

In [115]:
x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [116]:
x_train_embarked.shape

(712, 3)

In [117]:
x_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [118]:
x_train_age.shape

(712, 1)

In [119]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [120]:
x_train_sex.shape

(712, 2)

In [121]:
# concatenate all the array that we get

x_train_transformed = np.concatenate((x_train_remain,x_train_embarked,x_train_age,x_train_sex), axis= 1)
x_test_transformed  = np.concatenate((x_test_remain,x_test_embarked,x_test_age,x_test_sex), axis= 1)

In [122]:
x_train_transformed.shape

(712, 10)

In [123]:
x_test_transformed.shape

(179, 10)

# lets create the decision tree model


In [124]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

# lets predict the test model

In [125]:
y_pred = clf.predict(x_test_transformed)

In [126]:
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1], dtype=int64)

# lets see the accuracy 

In [128]:
from sklearn.metrics import accuracy_score

In [129]:
accuracy_score(y_test,y_pred)

0.7821229050279329

# import pickle

In [130]:
import pickle

In [132]:
pickle.dump(ohe_sex,open('models/sex_file.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))