In [1]:
import pickle

In [2]:
import numpy as np

In [10]:
ohe_sex = pickle.load(open('models/sex_file.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [5]:
# lets assume user input
# pclass/
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype = object).reshape(1,7)

In [6]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

# checking for ohe_sex

In [12]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\Asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [13]:
test_input_sex

array([[0., 1.]])

# ohe_embarked

In [15]:
test_input_emrbarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_emrbarked

array([[0., 0., 1.]])

# test_input_age

In [16]:
test`_input_age = test_input[:,2].reshape(1,1)

# lets concatenate all the variables

In [19]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_emrbarked),axis = 1)

In [20]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [21]:
test_input_transformed.shape

(1, 10)

In [22]:
clf.predict(test_input_transformed)
# bach jayega passenger

array([1], dtype=int64)

# so dekha kitna hetic hai pura yeha production ka code hai tjoda sa bhi edhar udhar hua toh  sab gadbad ho jayega